var num1 = 5;
var num2 = 9;
console.log(num1 + num2);
var num3 = 6;
var num4 = 4;
console.log(num3 + num4 + 9);
var num5 = 7 + 7;
num5 += 5;
console.log(num5);
var name1 = "Malaika";
var name2 = " zahid ";
var sum1 = name1 + name2;
console.log(sum1);
var num6 = 6 + 7;
num6++;
console.log(num6);
var num12 = 5;
var num13 = 7;
num12 = 4;
console.log(num12 + num13);
var num14 = 6 + 6 + 7 + 8;
console.log(num14);
var a = 4;
var b = 6;
console.log(a - b);
var c = 8;
var d = 4;
console.log(c - d);
var E = 10 - 8;
E--;
console.log(E);
var f = 7 - 3;
console.log(f);
var G = 9 - 2;
G -= 3;
console.log(G);
var num7 = 8;
var num8 = 7;
console.log(num7 * num8);
var num9 = 9 * 9;
console.log(num9);
var num10 = 7 * 5;
num10 *= 2;
console.log(num10);
var num11 = 6 * 6;
console.log(num11);
var num15 = 6;
var num17 = 7;
num17 = 2;
console.log(num15 * num17);
var num18 = 75;
var num19 = 8;
console.log(num18 / num19);
var H = 12 / 6;
console.log(H);
var i = 2 / 6;
i /= 4;
console.log(i);
var j = 25;
var k = 2;
k = 9;
console.log(j / k);
var l = 24 / 2;
console.log(l);
var M = 3;
var n = 6;
console.log(M % n);
var o = 5 % 7;
console.log(o);
var p = 3 % 9;
p %= 5;
console.log(p);
var Q = 56 % 7;
console.log(Q);
var R = 6;
var s = 4;
R = 5;
console.log(R % s);
var t = 6;
var u = 6;
console.log(Math.pow(t, u));
var v = Math.pow(2, 2);
console.log(v);
var w = Math.pow(3, 3);
console.log(w);
var x = Math.pow(7, 2);
x = Math.pow(4, 2);
console.log(x);
var y = Math.pow(3, 2);
console.log(y);
var z = Math.pow(5, 2);
console.log(z);
//comparison operator
console.log(5 == 6);
console.log(6 == 6);
console.log(2 == 8);
console.log(3 == 3);
console.log(5 == 7);
console.log(5 != 5);
console.log(5 != 4);
console.log(2 != 3);
console.log(1 != 1);
console.log(4 != 7);
console.log(5 < 8);
console.log(9 < 5);
console.log(4 < 6);
console.log(6 < 6);
console.log(7 < 1);
console.log(6 > 7);
console.log(4 > 4);
console.log(8 > 6);
console.log(7 > 5);
console.log(9 > 2);
console.log(4 <= 6);
console.log(4 >= 2);
console.log(7 >= 9);
console.log(9 >= 10);
console.log(6 >= 4);
