var name1 = " malaika";
console.log(name1);
name1 = "ruby";
console.log(name1);
//bio data 
var personname = "malaikazahid";
var age = 21;
var ismarried = false;
console.log(personname);
console.log(age);
console.log(ismarried);
var personname1 = "malaika";
var age2 = 21;
var isfollow = true;
var sign = null;
var pass = undefined;
console.log(personname1);
console.log(age2);
console.log(isfollow);
console.log(sign);
console.log(pass);
var apple = "green";
var banana = "yellow";
var cherry = "purple";
console.log(apple);
console.log(banana);
console.log(cherry);
